services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-defaultuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-defaultpassword}
      POSTGRES_DB: ${POSTGRES_DB:-defaultdatabase}
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - backend

  worker:
    build:
      context: ./worker
      args:
        POSTGRES_USER: ${POSTGRES_USER:-defaultuser}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-defaultpassword}
        POSTGRES_DB: ${POSTGRES_DB:-defaultdatabase}
    depends_on:
      - db
    networks:
      - backend

  node-red:
    build:
      additional_contexts:
        hostetc: /etc
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data
    devices:
      - /dev/snd:/dev/snd
    networks:
      - frontend

  web:
    build:
      context: ./web
      args:
        POSTGRES_USER: ${POSTGRES_USER:-defaultuser}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-defaultpassword}
        POSTGRES_DB: ${POSTGRES_DB:-defaultdatabase}
    ports:
      - "80:80"
    depends_on:
      - node-red
      - db
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
